### ISSUE TITLE
Missing Module (Validation) In Helpers

### ISSUE THREAD

**Issue by kallyas** [outboxafrica/edu_lookbook#14]
The Application is crashing before starting due to missing module Imported from helpers [helpers](https://github.com/outboxafrica/edu_lookbook/tree/develop/src/server/helpers)

https://github.com/outboxafrica/edu_lookbook/blob/0fb98a27dc6483437ff638559447970567d01197/src/server/routers/userRouter.js#L8

**Comment by 3Nakajugo** [comment]
hello @kallyas, this was fixed
