### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by kallyas** [outboxafrica/edu_lookbook#20]
On Testing endpoint signup that signs in a single user into the Application as given below,
| Endpoint      | Method            | Params       |Data type |
|:------------- |:-----------------:| :-----------:|---------:|
| `/api/users/signup`  | POST        | `None`   |`None`    | 

a `TypeError: Cannot read property 'startsWith' of undefined` is thrown 
as fired from https://github.com/outboxafrica/edu_lookbook/blob/96b635c4ad68ec11c6d43b8412758e02f3d095ae/src/server/helpers/validation.js#L13

and an status code of `403` is returned!
Should I think this endpoint requires authorization?

![image](https://user-images.githubusercontent.com/60466044/89729333-4bee7380-da3d-11ea-9b2c-5febbd3a34ae.png)

**Comment by davidgoodson** [comment]
Just tested this out and am not getting that kind of error, could please be more specific on how you got that error and which branch you had checkedout.

**Comment by kallyas** [comment]
I checked out the develop branch! 
Here is the error I get

![image](https://user-images.githubusercontent.com/60466044/89784741-db6d5280-db21-11ea-9942-8355ec7b4dcf.png)

These are my .env variables

![image](https://user-images.githubusercontent.com/60466044/89784851-12436880-db22-11ea-80a7-904c5eeb83c4.png)

I'm still getting the same Response! 403!

**Comment by davidgoodson** [comment]
That issue is on your side, the system uses a different kind of env file. Which is not shared online. The error you are gating is because your environment is undefined.

**Comment by kallyas** [comment]
Oh! well, are there any more `env` variables apart from these that I am Missing?

`PORT`
`DB_URL`
`SECRET `

**Comment by Roland-Sankara** [comment]
@kallyas Yes, there is some other `env` variable that you are missing:
`NODE_ENV`

**Comment by kallyas** [comment]
The Problem was with my set up environment
